[package]
name = "port_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.23.0", features = ["serialize"] }
prettytable-rs = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
